### ISSUE TITLE
宝塔启动命令+php启动错误

### ISSUE THREAD

**Issue by sjnhnp** [ifui/baota#2]
请问如何启动bt命令？

宝塔的命令本来是：bt

就会出现命令菜单

请问如何进入以下路径？

PATH 路径
网站默认路径
WEB_PATH=./wwwroot
日志
LOGS_PATH=./wwwlogs
宝塔备份
BACKUP_PATH=./backup
启动脚本路径
DOCKERSCRIPT_PATH=./DockerScript

**Comment by sjnhnp** [comment]
php7.4启动错误

server/php/74/sbin/php-fpm: error while loading shared libraries: libonig.so.2: cannot open shared object file: No such file or directory

php7.3也启动失败 错误是  libonig.so.23

**Comment by ifui** [comment]
镜像启动的时候自动启动所有`bt`服务, 且默认执行`/etc/init.d/bt default`命令, 如果需要修改默认执行命令,请在`app/app.sh`文件中进行设置

如果需要进入容器执行`bt`其他命令或者进入指定路径, 请输入`docker-compose exec app bash`进入容器内部执行

**Comment by ifui** [comment]
> 镜像启动的时候自动启动所有`bt`服务, 且默认执行`/etc/init.d/bt default`命令, 如果需要修改默认执行命令,请在`app/app.sh`文件中进行设置
> 
> 如果需要进入容器执行`bt`其他命令或者进入指定路径, 请输入`docker-compose exec app bash`进入容器内部执行



> php7.4启动错误
> 
> server/php/74/sbin/php-fpm: error while loading shared libraries: libonig.so.2: cannot open shared object file: No such file or directory
> 
> php7.3也启动失败 错误是 libonig.so.23



> php7.4启动错误
> 
> server/php/74/sbin/php-fpm: error while loading shared libraries: libonig.so.2: cannot open shared object file: No such file or directory
> 
> php7.3也启动失败 错误是 libonig.so.23

输入`docker-compose exec app bash`进入容器后执行`whereis libonig`看一下文件是否存在
![image](https://user-images.githubusercontent.com/46117570/84583069-e445ee80-ae26-11ea-8b35-2342cb68242c.png)
