### ISSUE TITLE
想请教下，为什么不把www目录整体放真机硬盘2而使用 volume 作持久化存储www目录呢？

### ISSUE THREAD

**Issue by ieras** [ifui/baota#4]
是因为很多运行环境的安装需要在/usr /etc 下写入一些文件吗？

**Comment by ifui** [comment]
> 是因为很多运行环境的安装需要在/usr /etc 下写入一些文件吗？

首先，Docker与宿主机之间的数据交互主要是采用Volume映射方式，所以数据也是存在真机硬盘上，这样迁移数据方便，也符合实际需求

很多运行环境的安装确实需要对etc目录一些地方也作持久化处理，由于宝塔环境安装的复杂性，这一方面我还是按照笨办法，所以这里当然也需要持久化处理，这里还有一些提升空间，下一步我会继续改进

**Comment by ieras** [comment]
感谢解答！不过我觉得也可以映射一个data目录(假设叫这名字吧)，这样用户安装数据库一类的环境的时候 可以手动配置到data目录里面，就如同现在的wwwroot和wwwlg目录那样

**Comment by ieras** [comment]
非常感谢该项目，这样我就可以删掉parallels Desktop了，这个当作本机开发环境太棒啦！
Mac系统如果用原生搭开发环境会导致机器内很多垃圾文件产生，实在不想真机搭建环境，有了这个东西太好啦！PD虚拟机占存储实在太惊人了！
再次感谢！希望越来越完美！

**Comment by ifui** [comment]
> 感谢解答！不过我觉得也可以映射一个data目录(假设叫这名字吧)，这样用户安装数据库一类的环境的时候 可以手动配置到data目录里面，就如同现在的wwwroot和wwwlg目录那样

感谢认可，下步我会将其添加进去，使得可配置性更高
