### ISSUE TITLE
可以再增加几个常用的环境服务端口，或许还不是很全，期待作者新版

### ISSUE THREAD

**Issue by ieras** [ifui/baota#5]
```
${REDIS_PORT}:6379
${MEMCACHED_PORT}:11211
####分割线#####
${DATA_PATH}:/www/data
```
如图
![image](https://user-images.githubusercontent.com/17443060/99510898-8d8aa500-29c2-11eb-923f-6114c34b2c6d.png)

```
# redis 端口
REDIS_PORT=6379
# memcached 端口
MEMCACHED_PORT=11211

# 数据库相关存储路径
DATA_PATH=./data
```
如图
![image](https://user-images.githubusercontent.com/17443060/99510943-9aa79400-29c2-11eb-8c42-f87554f900e5.png)

**Comment by ifui** [comment]
> ```
> ${REDIS_PORT}:6379
> ${MEMCACHED_PORT}:11211
> ####分割线#####
> ${DATA_PATH}:/www/data
> ```
> 如图
> ![image](https://user-images.githubusercontent.com/17443060/99510898-8d8aa500-29c2-11eb-923f-6114c34b2c6d.png)
> 
> ```
> # redis 端口
> REDIS_PORT=6379
> # memcached 端口
> MEMCACHED_PORT=11211
> 
> # 数据库相关存储路径
> DATA_PATH=./data
> ```
> 如图
> ![image](https://user-images.githubusercontent.com/17443060/99510943-9aa79400-29c2-11eb-8c42-f87554f900e5.png)
> 

感谢提供改进建议，下一版将会增加更多相关配置
